### ISSUE TITLE
HOW TO: Remove packages in target edge image e.g. dnf

### ISSUE THREAD

**Issue by dnoliver** [gicmo/rfe-demo#1] opened 2020-08-20 17:49 UTC
Hello,

I have successfully deployed a Red Hat 8.3 Beta Edge image with this project, thanks!
The edge installation booted in ostree mode, and I can do rpm-ostree install, very similar to Fedora IoT.
But I can also use dnf, and use it to try to install packages:

```shell
bash-4.4# dnf install nodejs
Failed to set locale, defaulting to C.UTF-8
Updating Subscription Management repositories.
Last metadata expiration check: 0:32:18 ago on Thu Aug 20 17:14:48 2020.
Dependencies resolved.
===============================================================================================================================================================================================================
 Package                                Architecture                 Version                                                                 Repository                                                   Size
===============================================================================================================================================================================================================
Installing:
 nodejs                                 x86_64                       1:10.21.0-3.module+el8.3.0+7074+acd21ec3                                rhel-8-for-x86_64-appstream-beta-rpms                       8.9 M
Installing dependencies:
 npm                                    x86_64                       1:6.14.4-1.10.21.0.3.module+el8.3.0+7074+acd21ec3                       rhel-8-for-x86_64-appstream-beta-rpms                       3.8 M
Installing weak dependencies:
 nodejs-full-i18n                       x86_64                       1:10.21.0-3.module+el8.3.0+7074+acd21ec3                                rhel-8-for-x86_64-appstream-beta-rpms                       7.3 M
Enabling module streams:
 nodejs                                                              10                                                                                                                                       

Transaction Summary
===============================================================================================================================================================================================================
Install  3 Packages

Total download size: 20 M
Installed size: 72 M
Is this ok [y/N]: y
Downloading Packages:
(1/3): npm-6.14.4-1.10.21.0.3.module+el8.3.0+7074+acd21ec3.x86_64.rpm                                                                                                          2.1 MB/s | 3.8 MB     00:01    
(2/3): nodejs-full-i18n-10.21.0-3.module+el8.3.0+7074+acd21ec3.x86_64.rpm                                                                                                      2.5 MB/s | 7.3 MB     00:02    
(3/3): nodejs-10.21.0-3.module+el8.3.0+7074+acd21ec3.x86_64.rpm                                                                                                                2.5 MB/s | 8.9 MB     00:03    
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                          5.7 MB/s |  20 MB     00:03     
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  installing package nodejs-full-i18n-1:10.21.0-3.module+el8.3.0+7074+acd21ec3.x86_64 needs 28MB on the / filesystem
  installing package nodejs-1:10.21.0-3.module+el8.3.0+7074+acd21ec3.x86_64 needs 60MB on the / filesystem
  installing package npm-1:6.14.4-1.10.21.0.3.module+el8.3.0+7074+acd21ec3.x86_64 needs 88MB on the / filesystem

Error Summary
-------------
Disk Requirements:
   At least 88MB more space needed on the / filesystem
```

I think it is failing because of the read only file system, and thinking it does not have enough space.

So, dnf is included by default in the edge compose, but is not usable. 
Is it possible to remove it using the Image Builder?

Thanks!

**Comment by mrguitar** [comment] 2020-08-20 19:49
Yes we are aware of this. I don't have the BZ handy, but we have PR open and it will be fixed in our nightlies very soon. In the meantime, just ignore DNF and it work as intended. Package layering is possible via `rpm-ostree install`, but we are intending for users to add packages via Image Builder so the additional repo/rpm metadata isn't sent over the wire.

**Comment by dnoliver** [comment] 2020-08-20 19:52
What about packages other than dnf that I want to get removed from the ostree deployment?
Is that PR going to allow removing any package? or it is just intended for removing dnf?

**Comment by mrguitar** [comment] 2020-08-20 20:08
As a design principle, packages cannot be removed from image types in Image Builder. There are pros & cons to this, but it's meant to provide a base level of functionality that users cannot hurt themselves by cutting into. Were there any other packages that you felt were problematic and should be removed?

**Comment by dnoliver** [comment] 2020-08-20 22:38
The first scenario where I would want to remove packages is for things that do not work in ostree environments. Packages like dnf or grubby, have their equivalent in rpm-ostree, so they should not be there. Actually, any package that wants to write something in the /usr will not work in ostree right? so, removing them from the ostree compose would be good

Other group of packages, like fwupd for example, makes little sense if the target device does not provide firmware updates trough LVFS or similar. So, I think I should also have the possibility to remove them. Another example here will be ModemManager, for devices that do not have a gsm module. 

For the security scenario, it will be better to trim down any unnecessary service or library that are not needed and just increase the attack surface. For example, sshd is installed and enabled by default apparently in the compose that I just generated.

And finally, we have the ostree dependency problem. If I have package A that I don't need and depends on B.1.0, and I want to install C that depends on B.1.1, ostree will tell me that there is a base package replacement and cannot proceed. So installing a third party package could fail because of this dependency locking. In that case, I would like package A removed, so I can install package B dependencies. I had that before with libxml being used by a dependency of a dependency https://bugzilla.redhat.com/show_bug.cgi?id=1788308 

So, removing packages and avoiding all those is useful

**Comment by mrguitar** [comment] 2021-04-28 21:53
dnoliver, thanks for the discussion here. I agree with most of the points you made. For the short-run we've struck the best balance we can for a base set of packages that's small, usable for 80% of our users, and supportable. I'll see if we have an RFE for removing of packages as this is not the first time it's come up. Thanks.

**Closed as completed by mrguitar** 2021-04-28 21:53 UTC
